name: Build and Push Docker Image
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: leewan98
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: leewan98/radheef:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RADHEEF_HOST }}
          username: ${{ secrets.RADHEEF_USER }}
          password: ${{ secrets.RADHEEF_PASSWORD }}
          script: |
            cd ${{ secrets.RADHEEF_DIR }}
            docker compose pull radheef
            docker compose down radheef
            docker compose up -d radheef
            docker system prune -f
